export enum InputEnum {
  TEXT = "text",
  EMAIL = "email",
  PASSWORD = "password",
  NUMBER = "number",
  DATE = "date",
  TIME = "time",
  DATETIME = "datetime",
  DATETIME_LOCAL = "datetime-local",
  MONTH = "month",
  WEEK = "week",
  URL = "url",
  TEL = "tel",
  SEARCH = "search",
  COLOR = "color",
  FILE = "file",
  HIDDEN = "hidden",
  IMAGE = "image",
  RANGE = "range",
  RESET = "reset",
  SUBMIT = "submit",
}
